// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `process_buffer`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

Future<SimpleAudioInfo> getAudioInfo({required String path}) =>
    RustLib.instance.api.crateApiGetAudioInfo(path: path);

Future<Float32List> readAudioSamples({
  required String path,
  required BigInt startSample,
  required BigInt count,
}) => RustLib.instance.api.crateApiReadAudioSamples(
  path: path,
  startSample: startSample,
  count: count,
);

class SimpleAudioInfo {
  final String? title;
  final String? artist;
  final int? sampleRate;
  final BigInt? totalSamples;
  final BigInt? durationMs;

  const SimpleAudioInfo({
    this.title,
    this.artist,
    this.sampleRate,
    this.totalSamples,
    this.durationMs,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      artist.hashCode ^
      sampleRate.hashCode ^
      totalSamples.hashCode ^
      durationMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SimpleAudioInfo &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          artist == other.artist &&
          sampleRate == other.sampleRate &&
          totalSamples == other.totalSamples &&
          durationMs == other.durationMs;
}
